sudo: false
language: groovy
jdk:
- oraclejdk8
branches:
  only:
    - master
    - dev
    - grails3
services:
  - mongodb
addons:
  apt:
    sources:
      - mongodb-3.2-precise
    packages:
      - mongodb-org-server
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
  - export TZ=Australia/Canberra
  - date
script:
  - ./grailsw --non-interactive test-app
  - ./gradlew -Dgrails.env=prod assemble
#  - ./grailsw refresh-dependencies --non-interactive
#  - ./grailsw test-app --non-interactive
#  - ./grailsw prod war --non-interactive
after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && travis_retry ./gradlew publish'
env:
  global:
  - secure: afqIu7SQ/GoytD1WjbYDBok8+8YPEYIwOGWM2jtx5JW5qVD+qRZIWL5CY0MWZix28MVGjafbta3TRhM7SWPVpm+O9fnaKmW5BP3ywex/Imu9t4MSXbMY0FTXk5HArMSHXB78pfTjqVpsUey8m8gC64kecN+c+cpcNCT+MRkHL7Q=
  - secure: WXXh59l5xUhIaMLbgCLE7b0AqCqN9Ms11r2YkU2SYg5z0pXeJVdbs7DX7oaE+OwOXyZOWnzugVbQv5USZ1v/FwDBNnr16jxXXGDT2+TL1myfS9YT+kj7zDf/OWtMzmebf5dj6OSi7/1qDQgCyElQZJIRpN8pENsC1qmDHPbEyMo=
